# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c93be8b636d3d94b588e9f415f9c22860edfd7e4e46940b55186211e51e6d65cb6c88b45242a87ce3052c59857705d270d976dce7da8e727181a17060f8caf1

test:
  secret_key_base: 937861fa26166c9338eb202a157a7ab636958c21e18f61342ed65c70705c972560d94b8bb66190a88f6ecf9077424b935f8c1637a6d44aae427e57ae72e17512

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
